### ISSUE TITLE
Comparison with lodash _.sortByOrder?

### ISSUE THREAD

**Issue by mgcrea** [jonschlinkert/array-sort#1]
I've recently used [lodash's `_.sortByOrder`](https://lodash.com/docs#sortByOrder) to perform multi-sorting of an array.
Would be interesting to add a small comparison with the lodash method in the readme.
Also benchmarks would be nice!

**Comment by jonschlinkert** [comment]
I can add something to the readme, not sure if it's faster than lodash though - or if that uses merge sort/stable sorting, etc.

fwiw, the reason I don't use the lodash modules is the size of the dependency tree. for example, `lodash.sortbyorder` module includes 109 files in and is 442k on disk (about the size of chalk... jk)

**Comment by jonschlinkert** [comment]
so far I have some basic benchmarks for a small array:

``` js
module.exports = [[
  { locals: { foo: 'bbb', date: '2013-05-06' }},
  { locals: { foo: 'aaa', date: '2012-01-02' }},
  { locals: { foo: 'ccc', date: '2014-01-02' }},
  { locals: { foo: 'ccc', date: '2015-01-02' }},
  { locals: { foo: 'bbb', date: '2014-06-01' }},
  { locals: { foo: 'aaa', date: '2014-02-02' }},
], ['locals.foo', 'locals.date']];
```

<img width="530" alt="screen shot 2015-07-18 at 9 09 49 am" src="https://cloud.githubusercontent.com/assets/383994/8761696/c99f324c-2d2c-11e5-9f69-de0526ed2fb9.png">

k, I'm going to take my 4yr old to breakfast : )  I'll do benchmarks for some larger data sets and add the results to the readme when I get a chance.

**Comment by jonschlinkert** [comment]
closing based on age
