### ISSUE TITLE
Add ES6 import

### ISSUE THREAD

**Issue by mesqueeb** [jonschlinkert/array-sort#11]
please add ES6 import method

**Comment by doowb** [comment]
There's no need, you can use the following statement and it will work:

```js
import sort from 'array-sort';
```

**Comment by mesqueeb** [comment]
Ok @doowb thanks. I just pushed readme update:
https://github.com/jonschlinkert/array-sort/pull/13/files#diff-8191924d78e7652d71643c49ac2716c8
