### ISSUE TITLE
comparison to null strings

### ISSUE THREAD

**Issue by jrhii** [jonschlinkert/array-sort#3]
It seems that if you are comparing strings in objects that may include `null` if won't sort properly.

**Comment by jrhii** [comment]
running this 

```
`const nullArray = new Array();

while (array.some(obj => obj[element] === null)) {
    array.forEach((obj, index) => {
        if (obj[element] === null) {
            array.splice(index, 1);
            nullArray.push(obj);
        }
    });
}`
```

and then concat `nullArray` to the end of my return fixes it for what I need it to do.

**Comment by jonschlinkert** [comment]
A more detailed code example would help, so we can reproduce. Like examples of what's in the arrays.

**Comment by vladshcherbin** [comment]
@jonschlinkert here is example:

```js
const test = [
  { title: 'b' },
  { title: null },
  { title: 'a' }
]

console.log(arraySort(test, 'title'))
```

Current output:

```js
[
  { title: 'a' },
  { title: null },
  { title: 'b' }
]
```

**Comment by doowb** [comment]
Thanks @VladShcherbin for the example. A new version with logic for handling `null` and `undefined` has been published.
